project:
  type: website

website:
  title: "openbudget-dashboard"
  sidebar:
    contents:
      - href: dashboard.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



